### ISSUE TITLE
Add readme and license

### ISSUE THREAD

**Issue by macalinao** [olliestanley/skyprint#2]
Maybe i'll add a readme generator to bukkit-bootstrap. but you need a readme on this plugin

**Comment by olliestanley** [comment]
you pr'd the bukkit-bootstrap readme

**Comment by olliestanley** [comment]
what license to use

**Comment by macalinao** [comment]
mit

**Comment by macalinao** [comment]
thats basically the "i don't care but give me credit" license

**Comment by olliestanley** [comment]
DONE
